### ISSUE TITLE
linux - /home/abe

### ISSUE THREAD

**Issue by yafp** [iabem97/komorebi#17]
I recently tested komorebi on an Ubuntu host and now realizing some really strange & disturbing issue.

On the first look, it looks like the system has a new local user account (created on the installation date) by the name _abe_ (pretty similar to this project developer name) which contains only a single file _komorebi.desktop_ within _/home/abe/.config/autostart_.

According to _/etc/passwd_ & _userdel_ it isn't an user account, so most likely komorebi is just creating & using _/home/abe_ for whatever reasons.

The desktop file is pointing to _/System/Resources_ and _/System/Applications_ both far away from typical install locations on linux systems.

Somehow this is kinda fishy. Any chance you can explain this?

**Comment by iabem97** [comment]
@yafp That's actually pretty strange.. Did you install Komorebi through a debian package or from source?
I've tried both methods on different computers and I was not able to replicate your issue.
I also did a search for 'abe' in the Komorebi source directory and I was not able to find anything relating to 'abe'.
From my understanding, you only have a folder with name 'abe', but no user. It might have been caused by a cached build files I believe..

Regarding /System, Komorebi follows Kedos's filesystem scheme. In other words, it was build like that on purpose.

You don't have anything to worry about regarding that issue. The source code is available and you can see that there's nothing referring to my username in any file.

**Comment by mvrozanti** [comment]
I too get the same error
