### ISSUE TITLE
Support for GIF and videos

### ISSUE THREAD

**Issue by joaoescribano** [iabem97/komorebi#25]
I don't really know it it's even possible but... I've found this repo after search looking for something to do this:

![Wallpaper](http://skillprogramming.com/images/pictuers/excelent_wallpaper_to_scare_people_it_is.gif)

So i't would be great if there is an option to just... render some gif or video on the background...

Thanks

**Comment by amasriSF** [comment]
That's a very cool wallpaper! I will be working on adding support in the future for enabling GIFs, video files, and possibly YouTube videos!
As of now, Komorebi is going under major overhaul and might take a while till I can deliver such feature. But keep up! I'll update this once the feature is added!
______
Thank you!

**Comment by joaoescribano** [comment]
:+1: 

Thanks so mutch!!!

**Comment by derpyderpaderp** [comment]
This is a good idea. I would really love something like this.

**Comment by amasriSF** [comment]
@joaoescribano @derpyderpaderp Komorebi 2.0 has been released with video wallpapers support!
Checkout this video with the zombie wallpaper set.
https://www.youtube.com/watch?v=EwtVA4pEHIk

Unfortunately, I can't share the wallpaper since it is copyrighted. But if you find it somewhere on the internet, you can probably use it!

**Comment by joaoescribano** [comment]
WOOOOOWWWWWWWWWWW

SUPER-DUPER-COOL!!!!!

Thanks so much!!!!!

**Comment by dirkdavidis** [comment]
where can i get this zombie clip?
